"use client";

import { useEffect, useState } from "react";
import { FileText, ArrowLeft, ChevronDown, ChevronUp } from "lucide-react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense } from "react";

const API = "http://localhost:8000/api";

interface Competitor {
  id: number;
  name: string;
  website_url: string;
}

interface Report {
  id: number;
  competitor_id: number;
  report_text: string;
  generated_at: string;
}

function ReportsContent() {
  const searchParams = useSearchParams();
  const preselectedId = searchParams.get("id");

  const [competitors, setCompetitors] = useState<Competitor[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(
    preselectedId ? parseInt(preselectedId) : null
  );
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(false);
  const [expanded, setExpanded] = useState<number | null>(null);

  useEffect(() => {
    fetch(`${API}/competitors`)
      .then((r) => r.json())
      .then((d) => {
        setCompetitors(d.competitors);
        if (!selectedId && d.competitors.length > 0) {
          setSelectedId(d.competitors[0].id);
        }
      });
  }, []);

  useEffect(() => {
    if (!selectedId) return;
    setLoading(true);
    fetch(`${API}/reports/${selectedId}`)
      .then((r) => r.json())
      .then((d) => {
        setReports(d.reports);
        if (d.reports.length > 0) setExpanded(d.reports[0].id);
      })
      .finally(() => setLoading(false));
  }, [selectedId]);

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      {/* Header */}
      <header className="border-b border-gray-800 bg-gray-900">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h1 className="text-lg font-bold text-white">Competitor Intelligence</h1>
              <p className="text-xs text-gray-400">Autonomous monitoring pipeline</p>
            </div>
          </div>
          <nav className="flex items-center gap-6 text-sm">
            <Link href="/" className="text-gray-400 hover:text-white transition">Dashboard</Link>
            <Link href="/competitors" className="text-gray-400 hover:text-white transition">Competitors</Link>
            <Link href="/reports" className="text-blue-400 font-medium">Reports</Link>
            <Link href="/trends" className="text-gray-400 hover:text-white transition">Trends</Link>
            <Link href="/battlecards" className="text-gray-400 hover:text-white transition">Battlecards</Link>
            <Link href="/timeline" className="text-gray-400 hover:text-white transition">Timeline</Link>
          </nav>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8">
        {/* Page header */}
        <div className="flex items-center gap-3 mb-8">
          <Link href="/" className="text-gray-400 hover:text-white transition">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div>
            <h2 className="text-2xl font-bold text-white">Intelligence Reports</h2>
            <p className="text-gray-400 text-sm">Weekly briefings generated by the pipeline</p>
          </div>
        </div>

        {/* Competitor selector */}
        <div className="flex gap-3 mb-6 flex-wrap">
          {competitors.map((comp) => (
            <button
              key={comp.id}
              onClick={() => setSelectedId(comp.id)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition ${
                selectedId === comp.id
                  ? "bg-blue-600 text-white"
                  : "bg-gray-800 text-gray-400 hover:text-white"
              }`}
            >
              {comp.name}
            </button>
          ))}
        </div>

        {/* Reports list */}
        {loading ? (
          <div className="text-center py-20">
            <div className="w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
            <p className="text-gray-400">Loading reports...</p>
          </div>
        ) : reports.length === 0 ? (
          <div className="text-center py-20 border border-dashed border-gray-700 rounded-xl">
            <FileText className="w-12 h-12 text-gray-600 mx-auto mb-4" />
            <p className="text-gray-400 text-lg mb-2">No reports yet</p>
            <p className="text-gray-600 text-sm mb-6">
              Run the pipeline to generate your first report
            </p>
            <Link
              href="/competitors"
              className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg text-sm transition"
            >
              Go to Competitors
            </Link>
          </div>
        ) : (
          <div className="space-y-4">
            {reports.map((report) => (
              <div
                key={report.id}
                className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden"
              >
                {/* Report header */}
                <button
                  onClick={() =>
                    setExpanded(expanded === report.id ? null : report.id)
                  }
                  className="w-full flex items-center justify-between p-5 hover:bg-gray-800 transition"
                >
                  <div className="flex items-center gap-3">
                    <FileText className="w-5 h-5 text-blue-400" />
                    <div className="text-left">
                      <p className="text-white font-medium">
                        Intelligence Brief —{" "}
                        {new Date(report.generated_at).toLocaleDateString(
                          "en-US",
                          {
                            weekday: "long",
                            year: "numeric",
                            month: "long",
                            day: "numeric",
                          }
                        )}
                      </p>
                      <p className="text-gray-500 text-sm">
                        {new Date(report.generated_at).toLocaleTimeString()} UTC
                      </p>
                    </div>
                  </div>
                  {expanded === report.id ? (
                    <ChevronUp className="w-5 h-5 text-gray-400" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-400" />
                  )}
                </button>

                {/* Report content */}
                {expanded === report.id && (
                  <div className="border-t border-gray-800 p-5">
                    <pre className="text-sm text-gray-300 whitespace-pre-wrap font-mono leading-relaxed bg-gray-800 rounded-lg p-4 overflow-auto max-h-[600px]">
                      {report.report_text}
                    </pre>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}

export default function ReportsPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-gray-950 flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin" />
      </div>
    }>
      <ReportsContent />
    </Suspense>
  );
}